### ISSUE TITLE
Google ISO codes for Hebrew and Javanese

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#484] opened 2023-06-16 12:44 UTC
The ISO code for Hebrew and Javanese is `he` and `jv`. However, there is an exception for Google, which has legacy codes `iw` and `jw`.

At the Google API page in Machine Translate, these are displayed as follows:
![image](https://github.com/machinetranslate/machinetranslate.org/assets/33723604/65d76da9-6a72-4c22-9f5b-f27643e74993)

`he o iw` and `jv o jw` and unrecognized codes and therefore break the hyperlink that takes the user to the Wikipedia article.
Pages for `he` and `jv` already exist.

**Comment by bittlingmayer** [comment] 2023-07-27 21:04
The issue is actually in the data file:

<img width="997" alt="Screenshot 2023-07-28 at 01 03 52" src="https://github.com/machinetranslate/machinetranslate.org/assets/11457984/69cf840d-da0d-4e1c-b90c-c2b536007871">

**Comment by bittlingmayer** [comment] 2023-07-28 20:21
It is displaying better, but still the name and link are not found.

<img width="612" alt="Screenshot 2023-07-29 at 00 19 23" src="https://github.com/machinetranslate/machinetranslate.org/assets/11457984/aad500e2-90e8-4181-9267-0e61fbafeef6">

**Comment by bittlingmayer** [comment] 2023-07-28 20:22
Probably needs to be fixed in generate.py

**Comment by bittlingmayer** [comment] 2023-07-28 20:34
Just needed to re-run generate.py

**Closed** 2023-07-28 20:33 UTC
Labels: bug, languages, apis
